/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomSearch: typeof import('./src/components/CustomSearch/CustomSearch.vue')['default']
    CustomSelect: typeof import('./src/components/CustomSearch/CustomSelect.vue')['default']
    CustomTable: typeof import('./src/components/CustomTable/CustomTable.vue')['default']
    CustomUpload: typeof import('./src/components/CustomUpload/CustomUpload.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptions: typeof import('element-plus/es')['ElOptions']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LayoutBottom: typeof import('./src/components/Layout/LayoutBottom.vue')['default']
    LayoutHeader: typeof import('./src/components/Layout/LayoutHeader.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    NavBarOptions: typeof import('./src/components/NavBar/NavBarOptions.vue')['default']
    NavMenu: typeof import('./src/components/NavMenu/NavMenu.vue')['default']
    PageBottom: typeof import('./src/components/Layout/PageBottom.vue')['default']
    PageHeader: typeof import('./src/components/Layout/PageHeader.vue')['default']
    RecursiveMenu: typeof import('./src/components/NavMenu/RecursiveMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/CustomSearch/Select.vue')['default']
  }
}
